modLoader = "javafml"
loaderVersion = "[${forge_version},)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "createtransportadditions"
version = "${version}"
displayName = "Create: Transport Additions"
authors = "K256"
description = ""

[[dependencies.createtransportadditions]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.createtransportadditions]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.createtransportadditions]]
modId="create"
mandatory=true
versionRange="${create_version}"
ordering="NONE"
side="BOTH"